# Generated by Django 5.1.4 on 2025-02-14 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('task', models.TextField()),
                ('date_of_reminder', models.DateField()),
                ('time_description', models.TimeField()),
            ],
        ),
    ]
